wandb_version: 1

exp_name:
  desc: null
  value: ppo_continous_action
gym_id:
  desc: null
  value: HalfCheetah-v4
learning_rate:
  desc: null
  value: 0.0003
seed:
  desc: null
  value: 1
total_timesteps:
  desc: null
  value: 2000000
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: cleanRL
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: true
num_envs:
  desc: null
  value: 1
num_steps:
  desc: null
  value: 2048
anneal_lr:
  desc: null
  value: true
gae:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 32
update_epochs:
  desc: null
  value: 10
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
batch_size:
  desc: null
  value: 2048
minibatch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    code_path: code/ppo_continous_action.py
    python_version: 3.8.10
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685095215.354366
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.10
      5: 0.15.1
      8:
      - 5
